// Fallback content — mirrors /app/backend/default_content.py so the UI never renders empty
// even when the API is unreachable (e.g. CMS not yet deployed).
export const FALLBACK_CONTENT = {
  hero: {
    overline: "№ 001 — Premium Wrapping",
    geo_label: "54.71° N / 20.51° E",
    studio_label: "Detailing Studio",
    title_line_1: "Преображаем",
    title_line_2: "автомобили в",
    title_line_3_grey: "произведение",
    title_line_3_white: " искусства",
    description: "Полиуретан. Винил. Антихром. Полная защита кузова в Калининграде — для тех, кто видит разницу в деталях.",
    cta_primary: "Рассчитать проект",
    cta_secondary: "Смотреть процесс",
    footer_meta: "PPF · Vinyl · Anti-chrome · Headlight Armor",
    footer_edition: "2026 / Edition 01",
    poster_url: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1920&q=85",
    video_url: "https://assets.mixkit.co/videos/35540/35540-720.mp4",
  },
  protocol: {
    overline: "001.5 — Protocol",
    title_line_1: "Протокол",
    title_line_2_grey: "безопасной",
    title_line_2_white: " оклейки.",
    description: "Каждый автомобиль проходит многоэтапную подготовку и контроль качества перед оклейкой. Не «наклеить плёнку» — а инженерный процесс.",
    footer_left: "Technology · Attention · Precision",
    footer_right: "Технология, внимание к деталям и precision-подход — основа безупречной оклейки.",
    stages: [
      { n: "01", title: "Подготовка автомобиля", overline: "Stage one — Surface", desc: "Многофазная мойка, удаление битума и металлических вкраплений, обезжиривание, очистка труднодоступных зон. Создаём идеально чистую поверхность для адгезии плёнки.", points: ["Многофазная мойка кузова","Удаление битума и вкраплений","Обезжиривание поверхности","Очистка труднодоступных зон"], video: "https://assets.mixkit.co/videos/35230/35230-720.mp4", poster: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=2000&q=85" },
      { n: "02", title: "Безопасная подготовка кузова", overline: "Stage two — Paint", desc: "Анализируем состояние ЛКП, устраняем мелкие дефекты, выполняем безопасную полировку. Работаем только профессиональным оборудованием — без перегрева и риска.", points: ["Анализ толщины ЛКП","Устранение мелких дефектов","Деликатная полировка","Подготовка под оклейку"], video: "https://assets.mixkit.co/videos/35205/35205-720.mp4", poster: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=2000&q=85" },
      { n: "03", title: "Точная оклейка и контроль", overline: "Stage three — Precision", desc: "Каждый элемент клеится вручную. Работаем по технологии: завод под кромки, отсутствие натяжений, контроль качества каждого узла перед выдачей автомобиля.", points: ["Заход плёнки под кромки","Без натяжений и клеевых растяжек","Покомпонентный QC","Финальная проверка покрытия"], video: "https://assets.mixkit.co/videos/35540/35540-720.mp4", poster: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=2000&q=85" },
    ],
  },
  before_after: {
    overline: "002 — Result",
    title_line_1: "Разница",
    title_line_2: "видна без слов.",
    description: "Перетащите ползунок — увидите состояние «до» и финальный результат после полной оклейки полиуретановой плёнкой.",
    before_image: "https://images.unsplash.com/photo-1616591938558-fb03d845567b?auto=format&fit=crop&w=1800&q=85",
    after_image: "https://images.unsplash.com/photo-1626381958625-f4e4ea343925?auto=format&fit=crop&w=1800&q=85",
    label_before: "До",
    label_after: "После",
    cta_label: "Получить расчёт",
    cta_text_mobile_strong: "Расчёт за\u00a015\u00a0минут",
    cta_text_mobile_prefix: "Хотите также? ",
    cta_text_mobile_suffix: " под Ваш автомобиль.",
  },
  services: {
    overline: "003 — Services",
    title_line_1: "Четыре направления.",
    title_line_2_grey: "Один",
    title_line_2_white: " стандарт качества.",
    description: "Каждая услуга — отдельный технологический процесс. Мы не делаем «всё подряд», поэтому делаем безупречно.",
    items: [
      { n: "01", title: "Полная оклейка полиуретаном", desc: "Невидимая броня PPF толщиной 200 мкм. Self-healing покрытие, защита от сколов и царапин на 10+ лет.", img: "https://images.pexels.com/photos/10126666/pexels-photo-10126666.jpeg?auto=compress&cs=tinysrgb&w=1400", alt: "Полная оклейка автомобиля полиуретановой плёнкой PPF в Калининграде", span: "md:col-span-2 md:row-span-2" },
      { n: "02", title: "Смена цвета винилом", desc: "От матового сатина до жидкого металла. Полная трансформация без покраски.", img: "https://images.unsplash.com/photo-1605036242577-8ee228902af1?auto=format&fit=crop&w=1200&q=80", alt: "Смена цвета автомобиля виниловой плёнкой — премиальный детейлинг Калининград", span: "md:col-span-2" },
      { n: "03", title: "Антихром", desc: "Превращаем все хромированные элементы в чёрный матовый или глянцевый.", img: "https://images.unsplash.com/photo-1680844540129-48dacc7d5d88?auto=format&fit=crop&w=1200&q=80", alt: "Антихром Mercedes-Benz BMW в Калининграде — затемнение хрома плёнкой", span: "" },
      { n: "04", title: "Защита зон риска", desc: "Капот, бампера, фары, пороги, ручки. Частичная оклейка от 1 дня.", img: "https://images.unsplash.com/photo-1592198084033-aade902d1aae?auto=format&fit=crop&w=1200&q=80", alt: "Антигравийная защита капота и бамперов автомобиля в Калининграде", span: "" },
    ],
  },
  configurator: {
    overline: "004 — Configurator",
    title_line_1: "Соберите свой",
    title_line_2: "автомобиль в новом цвете.",
    description: "Выберите тип плёнки, финиш и зону оклейки — мы пришлём точный расчёт в течение 15 минут.",
    form_heading: "Подберите необходимый вариант — а мы пришлём стоимость в течение\u00a015\u00a0минут.",
    form_description: "Без обязательств и навязчивых звонков. Свяжемся только по делу и предложим лучший вариант под ваш автомобиль.",
    trust_response_label: "Ответ", trust_response_value: "~15 мин",
    trust_warranty_label: "Гарантия", trust_warranty_value: "до 10 лет",
    trust_experience_label: "Опыт", trust_experience_value: "15+ лет",
  },
  stats: {
    overline: "007 — Numbers",
    title_line_1_white: "Почему ",
    title_line_1_grey: "мы.",
    title_line_2: "Без воды.",
    description: "Студия с командой мастеров, чьи руки видели больше углов, кромок и фар, чем некоторые целые сервисы.",
    items: [
      { value: 15, suffix: "+", label: "Лет precision-детейлинга" },
      { value: 300, suffix: "+", label: "Оклеенных автомобилей" },
      { value: 100, suffix: "%", label: "Контроль качества" },
      { value: 7, suffix: "", label: "Этапов процесса" },
    ],
  },
  gallery: {
    overline: "008 — Selected Works",
    title_line_1: "BMW.",
    title_line_2: "Серия избранных работ.",
    description: "Скрольте — галерея движется горизонтально. Каждый автомобиль — отдельная история точности.",
    cta_label: "Записаться на осмотр",
    cta_text_mobile_strong: "Приезжайте на осмотр",
    cta_text_mobile_prefix: "Хотите также? ",
    cta_text_mobile_suffix: " — подберём решение под Ваш автомобиль.",
    items: [
      { src: "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=2000&q=85", title: "BMW M4", meta: "PPF · Gloss", alt: "Оклейка BMW M4 полиуретановой плёнкой PPF в Калининграде" },
      { src: "https://images.unsplash.com/photo-1617814086367-b8cb20edbe98?auto=format&fit=crop&w=2000&q=85", title: "BMW M5", meta: "Vinyl · Matte", alt: "Смена цвета BMW M5 матовым винилом — премиум детейлинг" },
      { src: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=2000&q=85", title: "BMW X5 M", meta: "PPF · Stealth", alt: "BMW X5 M в плёнке stealth — полная защита кузова Калининград" },
      { src: "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=2000&q=85", title: "BMW G80", meta: "Anti-chrome", alt: "Антихром BMW G80 — затемнение хромированных элементов" },
      { src: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=2000&q=85", title: "BMW M3 Touring", meta: "Vinyl · Satin", alt: "BMW M3 Touring в сатиновом виниле — смена цвета авто Калининград" },
      { src: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=2000&q=85", title: "BMW i7", meta: "Full Wrap", alt: "BMW i7 — полная оклейка кузова виниловой плёнкой AUTOHAUS" },
    ],
  },
  contact: {
    overline: "009 — Contact",
    title_line_1: "Запишитесь",
    title_line_2_grey: "на бесплатный осмотр.",
    address_label: "Адрес",
    address: "Калининград, ул. Премиальная, 1",
    address_sub: "Цех — закрытая территория",
    phone_label: "Телефон",
    phone_display: "+7 (XXX) XXX-XX-XX",
    phone_link: "+70000000000",
    socials_label: "Контакты",
    socials: ["Instagram", "Telegram", "WhatsApp"],
    form_consent: "Отправляя форму, вы соглашаетесь на обработку персональных данных. Звоним и пишем только по делу.",
    submit_label: "Отправить заявку",
  },
  footer: {
    marquee: "AUTOHAUS · PRECISION · DETAILING · AUTOHAUS",
    brand: "AUTOHAUS",
    tagline: "Премиальная оклейка автомобилей в Калининграде с 2019 года.",
    nav_label: "Навигация",
    contacts_label: "Контакты",
    address_line_1: "Калининград,",
    address_line_2: "ул. Премиальная, 1",
    phone_display: "+7 (XXX) XXX-XX-XX",
    phone_link: "+70000000000",
    email: "hello@detailing-autohaus.ru",
    hours_label: "Часы",
    hours_line_1: "Пн–Сб · 09:00 — 21:00",
    hours_line_2: "Вс · по записи",
    copyright: "© 2026 AUTOHAUS — Все права защищены",
    tagline_right: "Made with precision · Kaliningrad",
  },
};

// Resolve a media URL: if it's a relative /api/... path, prefix with backend URL.
export function resolveMedia(url) {
  if (!url) return "";
  if (url.startsWith("/api/")) {
    return `${process.env.REACT_APP_BACKEND_URL}${url}`;
  }
  return url;
}
